import com.google.protobuf.ByteString;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import org.tron.tip899.fixture.Tip899FixtureProto;

/** Verifies protobufjs fixture bytes through protoc 3.25.8 generated Java classes. */
public final class Tip899ProtoInterop {
  private Tip899ProtoInterop() {}

  public static void main(String[] args) throws Exception {
    if (args.length != 6 || !"verify".equals(args[0])) {
      System.err.println(
          "usage: Tip899ProtoInterop verify <scheme-id> <public-key.bin> <signature.bin> "
              + "<pq-auth-sig.bin> <transaction-field.bin>");
      System.exit(2);
    }

    int scheme = Integer.parseInt(args[1]);
    byte[] publicKey = Files.readAllBytes(Path.of(args[2]));
    byte[] signature = Files.readAllBytes(Path.of(args[3]));
    byte[] expectedPQAuthSig = Files.readAllBytes(Path.of(args[4]));
    byte[] expectedTransactionField = Files.readAllBytes(Path.of(args[5]));

    Tip899FixtureProto.PQAuthSig value =
        Tip899FixtureProto.PQAuthSig.newBuilder()
            .setSchemeValue(scheme)
            .setPublicKey(ByteString.copyFrom(publicKey))
            .setSignature(ByteString.copyFrom(signature))
            .build();
    requireEqual("PQAuthSig generated bytes", expectedPQAuthSig, value.toByteArray());

    Tip899FixtureProto.PQAuthSig decoded =
        Tip899FixtureProto.PQAuthSig.parseFrom(expectedPQAuthSig);
    if (decoded.getSchemeValue() != scheme
        || !decoded.getPublicKey().equals(ByteString.copyFrom(publicKey))
        || !decoded.getSignature().equals(ByteString.copyFrom(signature))) {
      throw new IllegalStateException("PQAuthSig semantic decode mismatch");
    }

    Tip899FixtureProto.TransactionPQAuthSigField transaction =
        Tip899FixtureProto.TransactionPQAuthSigField.newBuilder().addPqAuthSig(value).build();
    requireEqual(
        "Transaction.pq_auth_sig field bytes", expectedTransactionField, transaction.toByteArray());
    Tip899FixtureProto.TransactionPQAuthSigField decodedTransaction =
        Tip899FixtureProto.TransactionPQAuthSigField.parseFrom(expectedTransactionField);
    if (decodedTransaction.getPqAuthSigCount() != 1
        || !decodedTransaction.getPqAuthSig(0).equals(value)) {
      throw new IllegalStateException("Transaction.pq_auth_sig semantic decode mismatch");
    }

    System.out.printf(
        "valid=true scheme=%d pqAuthSigLength=%d transactionFieldLength=%d%n",
        scheme, expectedPQAuthSig.length, expectedTransactionField.length);
  }

  private static void requireEqual(String label, byte[] expected, byte[] actual) {
    if (!Arrays.equals(expected, actual)) {
      throw new IllegalStateException(label + " mismatch");
    }
  }
}
